# MIT Licence
# Copyright (c) 2023 Simon Frankenberger
# Please see LICENCE.md for complete licence text.

FROM php:7.4.33-apache

# update system
RUN apt-get update \
    && apt-get dist-upgrade -y \
    # enable headers, rewrite and brotli module
    && a2enmod headers rewrite brotli \
    # install mysql driver
    && docker-php-ext-install pdo pdo_mysql \
    # install dependencies for gd lib
    && apt-get install -y libfreetype-dev libfreetype6 libgd3 libgd-dev libwebp-dev libwebp6 libzip-dev libzip4 zlib1g-dev zlib1g \
    # install gd lib
    && docker-php-ext-configure gd --with-jpeg --with-freetype --with-webp \
    && docker-php-ext-install gd \
    # install zip
    && docker-php-ext-install zip \
    # cleanup sources, apt cache and build dependencies
    && docker-php-source delete \
    && apt-get purge -y libfreetype-dev libgd-dev libwebp-dev libzip-dev zlib1g-dev \
    && rm -rf /var/lib/apt/lists/* \
    # install xdebug
    && pecl channel-update pecl.php.net \
    && pecl install xdebug-3.1.6 \
    # remove not needed packages
    && apt-get --purge -y autoremove \
    # clean apt cache
    && rm -rf /var/lib/apt/lists/*

HEALTHCHECK --interval=60s --timeout=2s \
    CMD curl --silent --fail  http://localhost/ || exit 1
