name: Run system tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.adoptopenjdk.net:443
            api.github.com:443
            auth.docker.io:443
            download-installer.cdn.mozilla.net:443
            download.mozilla.org:443
            downloads.gradle-dn.com:443
            downloads.gradle.org:443
            github.com:443
            github-cloud.githubusercontent.com:443
            jcenter.bintray.com:443
            objects.githubusercontent.com:443
            ocsp.digicert.com:80
            plugins.gradle.org:443
            plugins-artifacts.gradle.org:443
            production.cloudflare.docker.com:443
            r3.o.lencr.org:80
            raw.githubusercontent.com:443
            registry-1.docker.io:443
            repo.maven.apache.org:443
            services.gradle.org:443
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          lfs: true
      - run: docker compose pull --quiet && docker compose up -d
        working-directory: tests/src/test/resources/
      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
      - uses: browser-actions/setup-firefox@7eb6921a7449833b6356d5b61f7bba79b4e65ed3 # v1.5.1
        with:
          firefox-version: latest
      - uses: gradle/actions/wrapper-validation@31ae3562f68c96d481c31bc1a8a55cc1be162f83 # v3.4.1
      - run: ./gradlew --no-daemon check
        working-directory: tests/
      - uses: mikepenz/action-junit-report@ac30be7acb0a361e5492575ab42e47fcadec4928 # v4.2.2
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'tests/build/test-results/test/TEST-*.xml'
