name: Run system tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:

permissions:
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          disable-sudo: true
          egress-policy: audit
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
        with:
          lfs: true
      - run: docker-compose pull --quiet && docker-compose up -d
        working-directory: tests/src/test/resources/
      - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3.10.0
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
      - uses: browser-actions/setup-firefox@2904820ff2e2cfeadf033d26ce136d65509ce7fc # v1.1.0
        with:
          firefox-version: latest
      - run: ./gradlew --no-daemon check
        working-directory: tests/
      - uses: mikepenz/action-junit-report@4fa23552acda20a6a1d44f16224a90efbeb6c5f1 # v3.7.5
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'tests/build/test-results/test/TEST-*.xml'
