name: Run system tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.adoptopenjdk.net:443
            api.github.com:443
            auth.docker.io:443
            download-installer.cdn.mozilla.net:443
            download.mozilla.org:443
            downloads.gradle-dn.com:443
            downloads.gradle.org:443
            github.com:443
            github-cloud.githubusercontent.com:443
            jcenter.bintray.com:443
            objects.githubusercontent.com:443
            ocsp.digicert.com:80
            plugins.gradle.org:443
            plugins-artifacts.gradle.org:443
            production.cloudflare.docker.com:443
            r3.o.lencr.org:80
            raw.githubusercontent.com:443
            registry-1.docker.io:443
            repo.maven.apache.org:443
            services.gradle.org:443
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: true
      - run: docker compose pull --quiet && docker compose up -d
        working-directory: tests/src/test/resources/
      - uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
      - uses: browser-actions/setup-firefox@634a60ccd6599686158cf5a570481b4cd30455a2 # v1.5.4
        with:
          firefox-version: latest
      - uses: gradle/actions/wrapper-validation@94baf225fe0a508e581a564467443d0e2379123b # v4
      - run: ./gradlew --no-daemon check
        working-directory: tests/
      - uses: mikepenz/action-junit-report@ee6b445351cd81e2f73a16a0e52d598aeac2197f # v5
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'tests/build/test-results/test/TEST-*.xml'
