name: Run system tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: write

jobs:
  build:
    strategy:
      matrix:
        php: [7.4, 8.4]
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.adoptopenjdk.net:443
            api.github.com:443
            auth.docker.io:443
            download-installer.cdn.mozilla.net:443
            download.mozilla.org:443
            downloads.gradle-dn.com:443
            downloads.gradle.org:443
            github.com:443
            github-cloud.githubusercontent.com:443
            jcenter.bintray.com:443
            objects.githubusercontent.com:443
            ocsp.digicert.com:80
            plugins.gradle.org:443
            plugins-artifacts.gradle.org:443
            production.cloudflare.docker.com:443
            r3.o.lencr.org:80
            raw.githubusercontent.com:443
            registry-1.docker.io:443
            repo.maven.apache.org:443
            services.gradle.org:443
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          lfs: true
      - run: docker compose pull --quiet && docker compose up -d
        working-directory: tests/src/test/resources/
        env:
          PHP_VERSION: ${{ matrix.php }}
      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'gradle'
      - uses: browser-actions/setup-firefox@0bc507ddf224827e3b1af68e014d5e42ab93e795 # v1.7.2
        with:
          firefox-version: latest
      - uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v4
      - run: ./gradlew --no-daemon check
        working-directory: tests/
      - uses: mikepenz/action-junit-report@d9f48fc87bc235f7e214acf696ca5abc0a986f16 # v5
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'tests/build/test-results/test/TEST-*.xml'
