name: Run system tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.adoptopenjdk.net:443
            api.github.com:443
            auth.docker.io:443
            download-installer.cdn.mozilla.net:443
            download.mozilla.org:443
            downloads.gradle-dn.com:443
            downloads.gradle.org:443
            github.com:443
            github-cloud.githubusercontent.com:443
            jcenter.bintray.com:443
            objects.githubusercontent.com:443
            ocsp.digicert.com:80
            plugins.gradle.org:443
            plugins-artifacts.gradle.org:443
            production.cloudflare.docker.com:443
            r3.o.lencr.org:80
            raw.githubusercontent.com:443
            registry-1.docker.io:443
            repo.maven.apache.org:443
            services.gradle.org:443
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          lfs: true
      - run: docker compose pull --quiet && docker compose up -d
        working-directory: tests/src/test/resources/
      - uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
      - uses: browser-actions/setup-firefox@955a5d42b5f068a8917c6a4ff1656a2235c66dfb # v1.5.2
        with:
          firefox-version: latest
      - uses: gradle/actions/wrapper-validation@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4
      - run: ./gradlew --no-daemon check
        working-directory: tests/
      - uses: mikepenz/action-junit-report@db71d41eb79864e25ab0337e395c352e84523afe # v4.3.1
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'tests/build/test-results/test/TEST-*.xml'
