name: Run system tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: write

jobs:
  build:
    strategy:
      matrix:
        php: [7.4, 8.4]
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.adoptopenjdk.net:443
            api.github.com:443
            auth.docker.io:443
            download-installer.cdn.mozilla.net:443
            download.mozilla.org:443
            downloads.gradle-dn.com:443
            downloads.gradle.org:443
            github.com:443
            github-cloud.githubusercontent.com:443
            jcenter.bintray.com:443
            objects.githubusercontent.com:443
            ocsp.digicert.com:80
            plugins.gradle.org:443
            plugins-artifacts.gradle.org:443
            production.cloudflare.docker.com:443
            r3.o.lencr.org:80
            raw.githubusercontent.com:443
            registry-1.docker.io:443
            repo.maven.apache.org:443
            services.gradle.org:443
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true
      - run: docker compose pull --quiet && docker compose up -d
        working-directory: tests/src/test/resources/
        env:
          PHP_VERSION: ${{ matrix.php }}
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'gradle'
      - uses: browser-actions/setup-firefox@fcf821c621167805dd63a29662bd7cb5676c81a8 # v1.7.1
        with:
          firefox-version: latest
      - uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v4
      - run: ./gradlew --no-daemon check
        working-directory: tests/
      - uses: mikepenz/action-junit-report@bccf2e31636835cf0874589931c4116687171386 # v5
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'tests/build/test-results/test/TEST-*.xml'
